# 已修复问题<a name="ZH-CN_TOPIC_0225731125"></a>

已修复问题请参见[表1](#table249714911433)。

**表 1**  修复问题列表 <a name="table249714911433"></a>

|  ISSUE   |问题描述  |
|:---  |:----  |
| [I4JB57](https://gitee.com/src-openEuler/iSulad/issues/I4JB57) | 【20.03 SP3】isulad安装失败，报错because a fatal signal was delivered causing the control process to dump core |
| [I4JH6S](https://gitee.com/openEuler/openstack/issues/I4JH6S) | [20.03 LTS SP3][Train]openstack-neutron缺少依赖dibbler-client |
| [I4JNRA](https://gitee.com/openEuler/openstack/issues/I4JNRA) | [20.03 LTS SP3][Train]openstack-nova缺少python-monotonic依赖 |
| [I4JNT7](https://gitee.com/openEuler/openstack/issues/I4JNT7) | [20.03 LTS SP3][Train]openstack-neutron缺少python-os-xenapi |
| [I4JOTA](https://gitee.com/src-openEuler/iSulad/issues/I4JOTA) | iSulad从sp2升级到sp3有告警日志 |
| [I4JQEQ](https://gitee.com/src-openEuler/linux-sgx/issues/I4JQEQ) | 【x86】sp2升级到sp3时sgx-pck-id-retrieval-tool有告警信息 |
| [I4JQOB](https://gitee.com/src-openEuler/rubygem-sinatra/issues/I4JQOB) | SP3分支rubygem-sinatra代码构建失败 |
| [I4JQOD](https://gitee.com/src-openEuler/rubygem-rack-test/issues/I4JQOD) | SP3分支rubygem-rack-test代码构建失败 |
| [I4JQOG](https://gitee.com/src-openEuler/rubygem-rack-protection/issues/I4JQOG) | SP3分支rubygem-rack-protection代码构建失败 |
| [I4JQPB](https://gitee.com/src-openEuler/cyrus-sasl/issues/I4JQPB) | 【x86】sp3降级到sp2时cyrus-sasl-gssapi与cyrus-sasl报冲突 |
| [I4JQPH](https://gitee.com/src-openEuler/libxml2/issues/I4JQPH) | openEuler 20.03 SP3中libxml2-2.9.10-22版本库存在问题，导致clufter软件包编译失败 |
| [I4JQPU](https://gitee.com/src-openEuler/groff/issues/I4JQPU) | 【x86】sp3降级到sp2时groff与groff-base报文件冲突 |
| [I4JQRC](https://gitee.com/src-openEuler/abseil-cpp/issues/I4JQRC) | 【x86】sp3降级到sp2时abseil-cpp与grpc冲突 |
| [I4JQZJ](https://gitee.com/src-openEuler/linux-sgx/issues/I4JQZJ) | [x86]sgxsdk从sp3降级到sp2告警 |
| [I4JR0U](https://gitee.com/src-openEuler/rdma-core/issues/I4JR0U) | 【x86】rdma-core从sp3降级到sp2告警 |
| [I4JRT9](https://gitee.com/openEuler/openstack/issues/I4JRT9) | [20.03 LTS SP3][Train]Glance缺少glance-registry服务 |
| [I4JS4I](https://gitee.com/src-openEuler/tog-pegasus/issues/I4JS4I) | [x86] tog-pegasus-help从sp3降级到sp2时有告警信息 |
| [I4JSLU](https://gitee.com/src-openEuler/cups/issues/I4JSLU) | 【arm】cups从sp3降级到sp2告警 |
| [I4JSMI](https://gitee.com/src-openEuler/jack-audio-connection-kit/issues/I4JSMI) | 【arm/x86】jack-audio-connection-kit从sp3降级到sp2告警 |
| [I4JSOA](https://gitee.com/src-openEuler/bind/issues/I4JSOA) | 【arm/x86】bind-chroot从sp3降级到sp2告警 |
| [I4JVIE](https://gitee.com/openEuler/kernel/issues/I4JVIE) | 【20.03 SP3】【arm物理机】最小化安装，手动配置ipv4/ipv6，有告警信息：random: 7 urandom warning(s) missed due to ratelimiting |
| [I4JWWO](https://gitee.com/openEuler/openstack/issues/I4JWWO) | [20.03 LTS SP3][Train]Ironic缺少sendfile模块 |
| [I4JXOF](https://gitee.com/openEuler/kernel/issues/I4JXOF) | 【20.03 SP3】【arm物理机】最小化安装选择部分插件（容器管理 、开发工具），日志中有告警 |
| [I4JYR6](https://gitee.com/src-openEuler/iSulad/issues/I4JYR6) | [20.03 SP3][iSulad] isulad -h命令执行失败 |
| [I4JZYD](https://gitee.com/src-openEuler/fastdfs/issues/I4JZYD) | [20.03-LTS-SP3]arm上fastdfs包下fdfs_storaged /etc/fdfs/storage.conf start启动失败 |
| [I4K00Q](https://gitee.com/src-openEuler/isula-transform/issues/I4K00Q) | isula-transform 编译报错：/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/7.3.0/../../../../lib64/libisulad_img.so: undefined reference to `get_isulad_daemon_constants |
| [I4K0GO](https://gitee.com/src-openEuler/openssh/issues/I4K0GO) | 【SP3_虚拟镜像arm/x86】qcow2镜像安装系统后，向外部主机scp文件提示：-gt需要一元表达式 |
| [I4K0J8](https://gitee.com/src-openEuler/resource-agents/issues/I4K0J8) | 【20.03-LTS-SP3】【x86】ldirectord服务启动后有错误Failed to parse PID from file /run/ldirectord.ldirectord.pid |
| [I4K0O9](https://gitee.com/src-openEuler/iSulad/issues/I4K0O9) | [20.03 SP3][iSulad] 转测Repo源里的iSulad版本和lcr不匹配，无法启动容器 |
| [I4K0Z9](https://gitee.com/src-openEuler/rrdtool/issues/I4K0Z9) | 【20.03 LTS SP3】【arm/x86】rrdcached.socket服务stop之后未删除/tmp/rrdcached.sock文件 |
| [I4K1H8](https://gitee.com/src-openEuler/cyrus-sasl/issues/I4K1H8) | 【LTS-SP3-RC1】【arm/x86】用memcached+sasl的方式给memcached增加认证，客户端访问失败 |
| [I4K257](https://gitee.com/src-openEuler/iavf/issues/I4K257) | 【SP3-arm/x86】安装iavf有错误信息 |
| [I4K267](https://gitee.com/src-openEuler/rdma-core/issues/I4K267) | 【20.03 SP3】【x86 物理机】虚拟化安装不勾选插件，组raid盘安装系统，报错：Failed to get current device name and index |
| [I4K2AY](https://gitee.com/src-openEuler/linux-sgx/issues/I4K2AY) | 【sp3-x86】安装子包sgx-dcap-pccs出现告警信息 |
| [I4K2NC](https://gitee.com/openEuler/kernel/issues/I4K2NC) | 【20.03 SP3】【arm 物理机】net镜像虚拟化安装（选择全部插件），安装好物理机后组raid盘安装虚拟机，虚拟机messages有GPT报错 |
| [I4K34Z](https://gitee.com/src-openEuler/systemd/issues/I4K34Z) | 【20.03 SP3】【x86 物理机】使用net镜像配置anaconda-ks.cfg进行半自动化安装，日志中有 |
| [I4K36H](https://gitee.com/src-openEuler/perl-Crypt-OpenSSL-Random/issues/I4K36H) | 【20.03-LTS-SP3】【x86/arm】perl-Crypt-OpenSSL-Random源码包本地自编译失败 |
| [I4K36R](https://gitee.com/src-openEuler/abrt/issues/I4K36R) | 【SP3】卸载abrt-addon-ccpp有错误信息 |
| [I4K38E](https://gitee.com/src-openEuler/openal-soft/issues/I4K38E) | 【20.03-LTS-SP3】【x86/arm】openal-soft源码包本地自编译失败 |
| [I4K39F](https://gitee.com/src-openEuler/libffado/issues/I4K39F) | 【20.03-LTS-SP3】【x86/arm】libffado源码包本地自编译失败 |
| [I4K3EI](https://gitee.com/src-openEuler/nfs-utils/issues/I4K3EI) | 【20.03-LTS-SP3】【x86】nfs-blkmap服务停止状态failed.【arm】nfs-blkmap服务启动后状态failed |
| [I4K44V](https://gitee.com/src-openEuler/hibernate-validator/issues/I4K44V) | 【20.03-LTS-SP3】【x86/arm】hibernate-validator 源码包本地自编译失败 |
| [I4K46G](https://gitee.com/src-openEuler/mysql5/issues/I4K46G) | 【20.03-LTS-SP3】【x86/arm】mysql5 源码包本地自编译失败 |
| [I4K47B](https://gitee.com/src-openEuler/infinispan/issues/I4K47B) | 【20.03-LTS-SP3】【x86/arm】infinispan源码包本地自编译失败 |
| [I4K4LB](https://gitee.com/src-openEuler/python-urwid/issues/I4K4LB) | 【20.03-LTS-SP3】【x86/arm】python-urwid源码包本地自编译失败 |
| [I4K4M0](https://gitee.com/src-openEuler/hivex/issues/I4K4M0) | 【20.03-LTS-SP3】【x86/arm】hivex源码包本地自编译失败 |
| [I4K4M3](https://gitee.com/src-openEuler/python-execnet/issues/I4K4M3) | 【20.03-LTS-SP3】【x86/arm】python-execnet源码包本地自编译失败 |
| [I4K6ZX](https://gitee.com/src-openEuler/initial-setup/issues/I4K6ZX) | 【20.03 LTS SP3】【arm/x86】initial-setup.service启动失败 |
| [I4K7KS](https://gitee.com/src-openEuler/subscription-manager/issues/I4K7KS) | 【20.03 LTS SP3】【arm/x86】rhsm.service启动失败，rhsm-facts.service启动之后日志中报错：cannot watch /etc/rhsm/syspurpose |
| [I4K7LV](https://gitee.com/src-openEuler/jersey/issues/I4K7LV) | 【20.03-LTS-SP3】【x86/arm】jersey源码包本地自编译失败 |
| [I4K8JU](https://gitee.com/src-openEuler/sos/issues/I4K8JU) | [20.03-LTS-SP3-round-1]arm/x86上sos包下命令行执行报错 |
| [I4K97V](https://gitee.com/src-openEuler/flink/issues/I4K97V) | 【20.03-LTS-SP3】【x86/arm】flink源码包本地自编译失败 |
| [I4K9WR](https://gitee.com/src-openEuler/util-linux/issues/I4K9WR) | [SP3 util-linux] mount命令挂载提示：unable to apply new capability set |
| [I4KD1B](https://gitee.com/src-openEuler/dovecot/issues/I4KD1B) | 【20.03 LTS SP3】【arm/x86】执行dovecot-sysreport命令报错 |
| [I4KD51](https://gitee.com/src-openEuler/openvswitch/issues/I4KD51) | 【20.03-LTS-SP3】【arm/x86】openvswitch-ipsec.service启动失败；ovn-controller-vtep.service停止有错误日志ovn-ctl[12958]: [FAILED] |
| [I4KF89](https://gitee.com/src-openEuler/perl-Net-DNS/issues/I4KF89) | 【20.03-LTS-SP3】【x86/arm】perl-Net-DNS源码包本地自编译失败 |
| [I4KFG6](https://gitee.com/src-openEuler/obs-server/issues/I4KFG6) | 【20.03 LTS SP3】【arm/x86】obsapisetup服务启动失败 |
| [I4KFOU](https://gitee.com/src-openEuler/edac-utils/issues/I4KFOU) | 【20.03-LTS-SP3】【arm/x86】edac.service stop的命令使用方式错误 |
| [I4KH5Z](https://gitee.com/src-openEuler/clamav/issues/I4KH5Z) | 【20.03 LTS SP3】【arm/x86】执行clamonacc -w命令报错 |
| [I4KI3Q](https://gitee.com/openEuler/openstack/issues/I4KI3Q) | [20.03 LTS SP3][Train]openstack-heat-engine服务启动失败 |
| [I4KIA8](https://gitee.com/src-openEuler/hbase/issues/I4KIA8) | 【20.03 LTS SP3】【arm/x86】hbase-master.service服务启动之后没多久状态变为inactive |
| [I4KIFU](https://gitee.com/src-openEuler/avahi/issues/I4KIFU) | 【20.03 SP3】【arm 物理机】SP1向SP3全量升级，出现avahi子包冲突问题 |
| [I4KJFO](https://gitee.com/src-openEuler/openEuler-release/issues/I4KJFO) | 【20.03 SP3】【20.03 SP1】【arm 物理机】进行全量安装或scp，有报错：/etc/profile.d/system-info.sh: 第 17 行：[: -gt：需要一元表达式 |
| [I4KJZ0](https://gitee.com/openEuler/openstack/issues/I4KJZ0) | [20.03 LTS SP3][Queens][Rocky] Kolla-plugin缺少python2依赖 |
| [I4KKHH](https://gitee.com/src-openEuler/libdnf/issues/I4KKHH) | 【libdnf-arm/x86】降级fuse包出现校验报错 |
| [I4KQOC](https://gitee.com/src-openEuler/rpm/issues/I4KQOC) | 【plugin selinux-arm/x86】卸载selinux-policy包出现报错：plugin selinux：hook fsm_file_prepare failed |
| [I4KR8A](https://gitee.com/src-openEuler/selinux-policy/issues/I4KR8A) | 【SP3-arm/x86】全量操作中bind包调用selinx-policy导致升级、降级报错 |
| [I4MKK7](https://gitee.com/openEuler/kernel/issues/I4MKK7) | secGear特性arm部署trustzone时需要调用sfc这个driver |
| [I4KWHY](https://gitee.com/openEuler/openstack/issues/I4KWHY) | [20.03 LTS SP3][Train] python-lz4构建失败 |
| [I4KWWM](https://gitee.com/src-openEuler/ibus/issues/I4KWWM) | 【20.03 SP3】ibus从SP1向SP3升级异常 |
| [I4L2LL](https://gitee.com/src-openEuler/redis5/issues/I4L2LL) | [SP3 round2] 修改redis配置文件，appendonly no 修改为appendonly yes，重新启动，redis启动失败 |
| [I4L2P5](https://gitee.com/src-openEuler/redis5/issues/I4L2P5) | 【20.03 LTS SP3】redis-sentinel命令提示需要sentinel.conf与实际不符 |
| [I4L3G5](https://gitee.com/src-openEuler/abrt/issues/I4L3G5) | 【SP3-arm/x86】abrt-addon-ccpp从SP2升级到SP3有异常信息 |
| [I4L3J0](https://gitee.com/src-openEuler/zlib/issues/I4L3J0) | 【20.03-LTS-SP3】【x86/arm】zlib源码包本地自编译失败 |
| [I4L3KW](https://gitee.com/src-openEuler/iSulad/issues/I4L3KW) | 【iSulad-arm/x86】iSulad从SP2升级到SP3报错 |
| [I4L3Y3](https://gitee.com/src-openEuler/fakeroot/issues/I4L3Y3) | 【20.03 SP3】【arm/x86】fakeroot-help从sp3向sp1降级有失败信息 |
| [I4L40H](https://gitee.com/src-openEuler/ndctl/issues/I4L40H) | [20.03-LTS-SP3][arm物理机]安装最小化加标准插件，message日志报错：/usr/bin/ndctl: No such file or directory |
| [I4L435](https://gitee.com/src-openEuler/glibc/issues/I4L435) | 【20.03 SP3】【arm物理机】SP3全量降级时在进行glibc-common的降级时，全量降级进程突然中断，glibc-common单包降级有报错 |
| [I4L7H0](https://gitee.com/src-openEuler/jffi/issues/I4L7H0) | 【20.03-LTS-SP3】【x86/arm】jffi源码包本地自编译失败 |
| [I4L9F3](https://gitee.com/src-openEuler/dde/issues/I4L9F3) | 【openEuler 20.03 SP3 Test round 2 】【x86/arm】帮助手册内容显示异常 |
| [I4LCPM](https://gitee.com/src-openEuler/obs-server/issues/I4LCPM) | 【20.03 LTS SP3】【arm/x86】obsnotifyforward.service服务stop失败 |
| [I4LD5U](https://gitee.com/openEuler/kernel/issues/I4LD5U) | 【openEuler20.03 LTS SP3 RC2】【ARM】执行长稳sysfs用例中断，产生core文件。 |
| [I4LGFY](https://gitee.com/src-openEuler/python-pyasn1-modules/issues/I4LGFY) | 【20.03-LTS-SP3】【x86/arm】python-pyasn1-modules源码包本地自编译失败 |
| [I4LGLK](https://gitee.com/src-openEuler/python-SecretStorage/issues/I4LGLK) | [20.03-LTS-SP3-round-2]x86上执行keyring --list-backend命令 python-SecretStorage包下文件告警 |
| [I4LGW9](https://gitee.com/src-openEuler/openvswitch/issues/I4LGW9) | 【20.03-LTS-SP3】【arm/x86】openvswitch包中服务需明确前提selinux关闭 |
| [I4LH0S](https://gitee.com/src-openEuler/openvswitch/issues/I4LH0S) | 【20.03-LTS-SP3】【arm/x86】ovn-controller-vtep.service服务普通用户下操作，需添加相关说明;openvswitch相关服务需要使用service方式 |
| [I4LI21](https://gitee.com/src-openEuler/thrift/issues/I4LI21) | 【20.03-LTS-SP3】【x86/arm】thrift源码包本地自编译失败 |
| [I4LINP](https://gitee.com/src-openEuler/nbdkit/issues/I4LINP) | 【20.03-LTS-SP3】【x86/arm】nbdkit源码包本地自编译失败 |
| [I4LKO5](https://gitee.com/src-openEuler/anaconda/issues/I4LKO5) | [20.03-LTS-SP3]安装OS时主机名设置64字符保存成功，自定义磁盘分区时报主机名无效的错误 |
| [I4LMGH](https://gitee.com/openEuler/kernel/issues/I4LMGH) | [20.03-LTS-SP3]arm物理机u盘安装后，message报错arm-smmu-v3 arm-smmu-v3.0.auto: enable smmu mpam failed |
| [I4LNIU](https://gitee.com/src-openEuler/cockpit/issues/I4LNIU) | 【20.03 SP3】【arm/x86 物理机/虚拟机】SP3全量降级到SP1过程中，环境无法ssh连接 |
| [I4LQBP](https://gitee.com/src-openEuler/libvirt/issues/I4LQBP) | 20.03-LTS-SP3测试环境openstack的虚拟机创建失败 |
| [I4LU6M](https://gitee.com/src-openEuler/openEuler-release/issues/I4LU6M) | 【20.03-LTS-SP3】【arm】安装多国语言包并配置语言中文，ssh登录报错 |
| [I4LWI8](https://gitee.com/openEuler/kernel/issues/I4LWI8) | 【openEuler20.03 LTS SP3】【ARM/X86】KASAN模式执行syskaller用例，产生一些问题。 |
| [I4M1Y9](https://gitee.com/src-openEuler/findbugs/issues/I4M1Y9) | 【20.03-LTS-SP3】【x86/arm】findbugs源码包本地自编译失败 |
| [I4M1YJ](https://gitee.com/src-openEuler/narayana/issues/I4M1YJ) | 【20.03-LTS-SP3】【x86/arm】narayana源码包本地自编译失败 |
| [I4MJUD](https://gitee.com/src-openEuler/findutils/issues/I4MJUD) | 【20.03-LTS-SP3】【arm】findutils源码包本地自编译失败 |
| [I4MK2M](https://gitee.com/src-openEuler/grep/issues/I4MK2M) | 【20.03-LTS-SP3】【arm】grep源码包本地自编译失败 |
| [I4MN7Z](https://gitee.com/src-openEuler/glib2/issues/I4MN7Z) | 【20.03-LTS-SP3】【x86/arm】glib2源码包本地自编译失败 |
| [I4MOLU](https://gitee.com/src-openEuler/qpdf/issues/I4MOLU) | 【20.03-LTS-SP3】【arm】qpdf源码包本地自编译失败 |
| [I4MPHV](https://gitee.com/src-openEuler/m4/issues/I4MPHV) | 【20.03-LTS-SP3】【arm】m4源码包本地自编译失败 |
| [I4MPLF](https://gitee.com/src-openEuler/mozjs78/issues/I4MPLF) | 【20.03-LTS-SP3】【x86/arm】mozjs78源码包本地自编译失败 |
| [I4G5Y3](https://gitee.com/src-openEuler/hiredis/issues/I4G5Y3) | mem_size overflow in sdsMakeRoomFor |
| [I4JH3K](https://gitee.com/src-openEuler/opusfile/issues/I4JH3K) | Abort in op_pcm_seek_page |
| [I4JH69](https://gitee.com/src-openEuler/opusfile/issues/I4JH69) | Unexpect-shift in op_rescale64 |
| [I4JH8T](https://gitee.com/src-openEuler/opusfile/issues/I4JH8T) | integer overflow in op_pcm_total |
| [I4M2YM](https://gitee.com/src-openEuler/tuned/issues/I4M2YM) | [20.03-lts-Sp3 round3-X86] powertop2tuned提示版本过低 |
| [I4M3MM](https://gitee.com/src-openEuler/sleuthkit/issues/I4M3MM) | 【fuzz测试】堆溢出 |
| [I4M5DO](https://gitee.com/openEuler/kernel/issues/I4M5DO) | 【openEuler20.03 LTS SP3】【ARM/X86】UBSAN模式执行syskaller用例，产生一些问题。 |
| [I4M8FM](https://gitee.com/src-openEuler/openvswitch/issues/I4M8FM) | 【20.03-LTS-SP3】【arm/x86】openvswitch-ipsec.service启动日志中存在ipsec.service启动失败信息，且导致ipsec.service无法成功启动 |
| [I4M92Z](https://gitee.com/src-openEuler/openEuler-latest-release/issues/I4M92Z) | sp3版本中openEuler-latest内容与实际不符 |
| [I4MC30](https://gitee.com/src-openEuler/libdb/issues/I4MC30) | 【20.03 SP3】【x86物理机】sp1升级到sp1 update，然后升级到sp3，reboot后有报错：Error: rpmdb open failed |
| [I4MC4O](https://gitee.com/src-openEuler/ncurses/issues/I4MC4O) | 【20.03 SP3】LTS全量升级到SP3，reboot后执行全量降级，降级结束后一段时间后有报错打印：awk: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory，机器无法ssh连接 |
| [I4MCP6](https://gitee.com/src-openEuler/initial-setup/issues/I4MCP6) | 【20.03 LTS SP3】【arm/x86】initial-setup从SP2到SP3及从SP2到SP2_update最新版到SP3升级有错误 |
| [I4MFP9](https://gitee.com/openEuler/nvwa/issues/I4MFP9) | nvwa配置服务热迁移，需要systremd接管进程，nvwa文档请补充systemd相关约束说明 |
| [I4MGLC](https://gitee.com/src-openEuler/sleuthkit/issues/I4MGLC) | 【fuzz】sleuthkit_fls_ntfs_fuzzer heap-buffer-overflow |
| [I4MIF3](https://gitee.com/src-openEuler/etmem/issues/I4MIF3) | memRouter策略+uswap无法按照预期将进程内存交换出去 |
| [I4ML4S](https://gitee.com/src-openEuler/booth/issues/I4ML4S) | 【LTS-SP3-RC3】【arm/x86】卸载booth-arbitrator包时提示booth@.service服务停止失败 |
| [I4MNHQ](https://gitee.com/openEuler/oemaker/issues/I4MNHQ) | 执行oemaker -s ${yum_repo} -r abc_123_flag -v R888C00 -p all_is_new999  失败后，执行oemaker -s ${yum_repo} -r abc -v R8 -p all，有mv报错 |
| [I4MNLZ](https://gitee.com/openEuler/oemaker/issues/I4MNLZ) | 直接执行oemaker构建，当repo源访问不了时，会多次提示“Cannot download repomd.xml: Cannot download repodata/repomd.xml” |
| [I4N1TO](https://gitee.com/openEuler/kernel/issues/I4N1TO) | 【openEuler 20.03 LTS SP3】【Arm/x86】ltp执行finit_module02用例失败 |
| [I4NFMS](https://gitee.com/openEuler/openstack/issues/I4NFMS) | [20.03 LTS SP3][Train] openstack-swift多个服务无法启动 |
| [I4NKIO](https://gitee.com/src-openEuler/trafficserver/issues/I4NKIO) | [20.03-LTS-SP3][arm/x86]trafficserver.service服务stop后状态显示为failed |
| [I4OH8P](https://gitee.com/src-openEuler/gcc/issues/I4OH8P) | 【20.03-LTS-SP3】【arm/x86】gcc源码包本地自编译失败 |